const cards = [
  {id: 1, name: "Cyber Glasses", current_dib: 3.45, img: "/img/card1.png", author: 7},
  {id: 2, name: "Neon Shades", current_dib: 2.15, img: "/img/card2.png", author: 15},
  {id: 3, name: "Crystal Vision", current_dib: 4.78, img: "/img/card3.png", author: 3},
  {id: 4, name: "Digital Mask", current_dib: 1.23, img: "/img/card1.png", author: 19},
  {id: 5, name: "Holographic Goggles", current_dib: 5.67, img: "/img/card3.png", author: 12},
  {id: 6, name: "Quantum Lenses", current_dib: 2.89, img: "/img/card2.png", author: 8},
  {id: 7, name: "Solar Filter", current_dib: 1.45, img: "/img/card1.png", author: 4},
  {id: 8, name: "Pixelated Vision", current_dib: 3.21, img: "/img/card3.png", author: 16},
  {id: 9, name: "Neural Interface", current_dib: 6.54, img: "/img/card2.png", author: 11},
  {id: 10, name: "Virtual Reality Set", current_dib: 2.34, img: "/img/card1.png", author: 2},
  {id: 11, name: "Augmented Glasses", current_dib: 4.12, img: "/img/card3.png", author: 18},
  {id: 12, name: "Laser Focus", current_dib: 1.67, img: "/img/card2.png", author: 6},
  {id: 13, name: "Bio-Optic Implants", current_dib: 7.89, img: "/img/card1.png", author: 14},
  {id: 14, name: "Cyberpunk Monocle", current_dib: 3.76, img: "/img/card3.png", author: 9},
  {id: 15, name: "Digital Binoculars", current_dib: 2.11, img: "/img/card2.png", author: 20},
  {id: 16, name: "HUD Glasses", current_dib: 5.43, img: "/img/card1.png", author: 5},
  {id: 17, name: "Night Vision Goggles", current_dib: 4.56, img: "/img/card2.png", author: 13},
  {id: 18, name: "Thermal Imaging", current_dib: 6.78, img: "/img/card3.png", author: 1},
  {id: 19, name: "X-Ray Specs", current_dib: 3.33, img: "/img/card3.png", author: 17},
  {id: 20, name: "Future Sight", current_dib: 8.91, img: "/img/card1.png", author: 10},
  {id: 21, name: "Data Stream Glasses", current_dib: 2.67, img: "/img/card2.png", author: 7},
  {id: 22, name: "AI Vision Assistant", current_dib: 5.21, img: "/img/card1.png", author: 15},
  {id: 23, name: "Quantum Eye", current_dib: 7.12, img: "/img/card3.png", author: 3},
  {id: 24, name: "Neural Optics", current_dib: 4.89, img: "/img/card2.png", author: 19},
  {id: 25, name: "Cyber Retina", current_dib: 3.09, img: "/img/card2.png", author: 12},
  {id: 26, name: "Digital Iris", current_dib: 6.45, img: "/img/card3.png", author: 8},
  {id: 27, name: "Smart Contact Lenses", current_dib: 2.78, img: "/img/card2.png", author: 4},
  {id: 28, name: "Holographic Display", current_dib: 5.67, img: "/img/card1.png", author: 16},
  {id: 29, name: "Virtual Eyewear", current_dib: 3.91, img: "/img/card3.png", author: 11},
  {id: 30, name: "Augmented Reality Mask", current_dib: 7.34, img: "/img/card2.png", author: 2},
]

module.exports = cards;
